name: Build LEDE OpenWrt Firmware

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Lede Firmware
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

<<<<<<< Updated upstream
      - name: Show workspace files
        run: ls -la
=======
      - name: 调试打印根目录全部文件
        run: ls -la

      - name: 清理磁盘空间(关键，防止磁盘爆满失败)
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo apt clean
>>>>>>> Stashed changes

      - name: Clear git proxy config
        run: |
          git config --global --unset-all url."https://mirror.ghproxy.com/https://github.com".insteadOf || true

      - name: Cache ccache & dl download
        uses: actions/cache@v4
        with:
          path: |
            .ccache
            lede/dl
          key: ${{ runner.os }}-lede-cache-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-lede-cache-

      - name: Run build script
        run: |
          export FORCE_UNSAFE_CONFIGURE=1
          ./lede_build.sh

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: lede-firmware
          path: firmware/*.zip
          retention-days: 30
